name: Build AndroidAPS APK

on:
  workflow_dispatch:
    inputs:
      tagName:
        description: 'Select AAPS Version'
        required: true
        default: '3.4.2.2'
        type: choice
        options:
          - 3.4.2.2
          - 3.4.2.1
          - 3.4.2.0
          - 3.4.1.0
          - 3.4.0.0
          - 3.3.2.1
          - 3.3.2.0
          - 3.3.1.3
          - 3.2.0.4
          - 3.2.0.3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout AndroidAPS
        uses: actions/checkout@v4
        with:
          repository: nightscout/AndroidAPS
          ref: ${{ github.event.inputs.tagName }}

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Enable Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleFullRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: androidaps-apk
          path: app/build/outputs/apk/full/release/*.apk
